apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Generic Release Trigger
on:
  workflow_call:
    inputs:
      component_name:
        type: string
        required: true
        description: "Component name (e.g. 'jellyfish-notifications')"
      component_id:
        type: string
        required: true
        description: "CloudBees Unify component ID (e.g. '0412edae-fc75-4ff4-9bd4-8b5875513aeb')"
      version:
        type: string
        required: true
        description: "Version to deploy (from build output)"
      smart_tests_build_name:
        type: string
        required: false
        default: ""
        description: "Smart Tests build name from test job (for E2E test linking)"
      environment:
        type: string
        required: false
        default: "squid-preprod"
        description: "Target environment for release"
      release_name_prefix:
        type: string
        required: false
        default: ""
        description: "Release name prefix (defaults to shortened component name)"
      ignore_releases:
        type: string
        required: false
        default: "rel-test-sb--squid-demo-3-20260202-114850-23326"
        description: "Comma-delimited list of release names to ignore when checking for concurrent releases (useful for stuck releases)"

jobs:
  trigger-release:
    steps:
      - name: Create and run CloudBees Unify release
        id: release
        uses: guru-actions/create_release@main
        with:
          cb_api_token: ${{ secrets.sb_internal_api }}
          cb_org_id: "11408510-e5d4-4d13-b1be-2c9b28f15aae"
          cb_application_id: "d2de1f29-84da-4eb7-ae91-060d2665e752"
          cb_workflow_id: "9c4f4616-957b-4cd0-8402-a443f93bf559"
          cb_environment: ${{ inputs.environment }}
          release_name_prefix: ${{ inputs.release_name_prefix != '' && inputs.release_name_prefix || format('{0}-', inputs.component_name) }}
          component_overrides: "${{ inputs.component_id }}=${{ inputs.version }}"
          close_on_pass: "true"
          skip_release_on_missing_artifacts: "false"
          selection_report_format: "markdown"
          prevent_concurrent_releases: "wait"
          queue_check_sleep_seconds: "45"
          wait_sleep_seconds: "45"
          max_wait_attempts: "90"
          enable_api_diagnostics: "false"
          smart_tests_component: ${{ inputs.component_name }}
          smart_tests_build_name: ${{ inputs.smart_tests_build_name }}
          ignore_releases: ${{ inputs.ignore_releases }}

      - name: Show release status
        uses: docker://alpine:3.18
        run: |
          echo "==================== RELEASE STATUS ===================="
          echo "Component: ${{ inputs.component_name }}"
          echo "Version: ${{ inputs.version }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Status: ${{ steps.release.outputs.status }}"
          echo "Release ID: ${{ steps.release.outputs.release_id }}"
          echo "Release Name: ${{ steps.release.outputs.release_name }}"
          echo "Run ID: ${{ steps.release.outputs.run_id }}"
          echo "========================================================"

      - name: Publish release link evidence
        kind: deploy
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          format: MARKDOWN
          content: |
            ## CloudBees Unify Release

            **Component:** ${{ inputs.component_name }}
            **Version:** ${{ inputs.version }}
            **Environment:** ${{ inputs.environment }}
            **Status:** ${{ steps.release.outputs.status }}

            **Release Name:** `${{ steps.release.outputs.release_name }}`
            **Release ID:** `${{ steps.release.outputs.release_id }}`
            **Run ID:** `${{ steps.release.outputs.run_id }}`

            ### 🔗 Release Link
            [View Release in CloudBees Unify](https://cloudbees.io/cloudbees/11408510-e5d4-4d13-b1be-2c9b28f15aae/applications/d2de1f29-84da-4eb7-ae91-060d2665e752/releases/${{ steps.release.outputs.release_id }}?organizationId=11408510-e5d4-4d13-b1be-2c9b28f15aae)

      - name: Publish component selection evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          format: MARKDOWN
          content: ${{ steps.release.outputs.selection_report }}
